Mobile-version portfolio
Tracy-miranja/mobile-version- pull request #1
Opened 2023-01-11 19:31 UTC by Tracy-miranja

I created my first section of mobile portfolio.

2023-01-11 20:18 UTC, Felix45 reviewed
Hi @Tracy-miranja , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights :heavy_check_mark: 
- [ ] All linter checks are setup and passing with green checks :heavy_check_mark: 
- [ ] Professional and descriptive readme file :heavy_check_mark: 

<img src="https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif" />

## Required Changes ♻️
- [ Required ] Please consider moving the `.menu` div into the `nav` tag. It's considered good practice to wrap menus inside the semantic `nav` tag since it makes it easier for persons using assistive web technologies like screen readers to easily identify menus on a webpage.

- [ Required ] Please consider wrapping the text `TRACY MIRANJA` using an anchor `a` tag instead of a `p` tag. This text is meant to be the `logo` of your portfolio so it's better to wrap it in an `a` tag instead of a `p` tag.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 20:18 UTC, Felix45 commented on style.css
> +  color: color-hex-case "#6070ff";
- [ Required ] Please consider fixing this `CSS` rule, the value of the `CSS` color property should be a valid color e.g `#6070ff` You can fix this by rectifying the value to `#6070ff` as shown below.
```CSS
 color: #6070ff
```

2023-01-11 20:18 UTC, Felix45 commented on style.css
> +@import url('https://fonts.googleapis.com/css2?family=Crete+Round&family=Inter&family=Roboto&display=swap');
- [ Required ] Please consider changing the `font-family` used on this page to `Poppins` since the `font-family` used on the template is `Poppins`. You can import the `Poppins` font family in the same way you've imported `Roboto` font in this file, see the example below on how you can do this.
```CSS
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap');
```
## Figma design
<img src="https://user-images.githubusercontent.com/16392046/211905221-de2c13a4-a07e-43f7-a35c-d8e6def622b1.png" width="250px" />

## Your implementation
<img src="https://user-images.githubusercontent.com/16392046/211905024-f6546612-b92f-40be-aa1b-a2f229f4a426.png" width="250px" />

2023-01-12 08:41 UTC, iambenkis requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Tracy-miranja  👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project, but you are almost there!

## To Highlight 🎉

- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark: 
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️

- [ ] Make sure you stick as much as possible to the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)

_Check the comments under this block_

## Optional suggestions

- [ ] [**OPTIONAL**]Your PR summary should be descriptive , it should contain the requirements you did in your branch :+1: , always make sure you submit a project with a description summary, it makes your request more professional :+1: and it makes cause your project to be invalidated, to avoid that, Get Inspire but [this summary](https://github.com/iambenkis/Space-X-/pull/32#issue-1401431050)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@iambenkis** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 08:41 UTC, iambenkis commented on index.html
> +        <ul class="links">
- [ ] As requested by the previous reviewer :recycle: , you should stick as much as possible to the Figma design. Always look at the requirements as something asked by a client. Kindly make should the margin, the padding , the fonts ,,, etc. are the same in your design as they are in the Figma template.

Your design 

![Screenshot from 2023-01-12 10-28-34](https://user-images.githubusercontent.com/80458199/212016329-5b8018ac-d64f-4022-beda-a7c7e2721db0.png)


Figma design


![Screenshot from 2023-01-12 10-30-01](https://user-images.githubusercontent.com/80458199/212016558-3fe83132-3c96-47c4-b6a9-caa644d126a8.png)

2023-01-12 11:17 UTC, MaganaAsiati approved these changes
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @Tracy-miranja , I'm @MaganaAsiati , your reviewer for this PR  :wave: 
Great work on making the changes requested by a previous reviewer 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


<img src="https://media2.giphy.com/media/ByeYxURXxPyptxD2ta/giphy-downsized-medium.gif"/>


## Highlights
- Descriptive pull request :heavy_check_mark:👨🏻‍💻
- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future.
- [ ] Check the comments under the review.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
Cheers and Happy coding! 🤓 👏👏👏

2023-01-12 11:31 UTC, merged